fix: direct-to-shard transactions don't need two-phase commit (#1614)
### Problem

When `two_phase_commit` is enabled, any transaction that's bound to one
shard only, e.g., `SET pgdog.shard` or `SET pgdog.sharding_key` result
in:

```
ERROR: 2pc commit supported with multi-shard binding only
```

### Solution

2pc doesn't need to run on single-shard transactions, so let's not.